const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  CATEGORY_ALL:'CATEGORY_ALL',
  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPLOAD: 'CATEGORY_UPLOAD',

  PRODUCT_ALL:'PRODUCT_ALL',
  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPLOAD: 'PRODUCT_UPLOAD',
  
  SUPPLIER_ALL:'SUPPLIER_ALL',
  SUPPLIER_LOADING: 'SUPPLIER_LOADING',
  SUPPLIER_CREATE: 'SUPPLIER_CREATE',
  SUPPLIER_UPLOAD: 'SUPPLIER_UPLOAD',

}

export default TYPES