const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  CATEGORY_ALL:'CATEGORY_ALL',
  CATEGORY_BY_ID:'CATEGORY_BY_ID',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPLOAD: 'CATEGORY_UPLOAD',
  CATEGORY_LOADING: 'CATEGORY_LOADING',
  
  PRODUCT_ALL:'PRODUCT_ALL',
  PRODUCT_BY_ID:'PRODUCT_BY_ID',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPLOAD: 'PRODUCT_UPLOAD',
  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_DELETE: 'PRODUCT_EDIT',
  
  SUPPLIER_ALL:'SUPPLIER_ALL',
  SUPPLIER_BY_ID:'SUPPLIER_BY_ID',
  SUPPLIER_CREATE: 'SUPPLIER_CREATE',
  SUPPLIER_UPLOAD: 'SUPPLIER_UPLOAD',
  SUPPLIER_LOADING: 'SUPPLIER_LOADING',
  
  CLIENT_ALL:'CLIENT_ALL',
  CLIENT_BY_ID:'CLIENT_BY_ID',
  CLIENT_CREATE: 'CLIENT_CREATE',
  CLIENT_UPLOAD: 'CLIENT_UPLOAD',
  CLIENT_LOADING: 'CLIENT_LOADING',
  
}

export default TYPES